Chieh H Chang (title:Network and Computer System Administrator) and a brief description:
- Establish a framework to achieve program objectives focused on cost reduction, increased productivity, and enhanced user satisfaction.
- Measure strengths and weaknesses of programs and processes, implementing necessary changes.
- Provide technical support for staff and faculty across over 10 academic departments and centers.
- Support daily technology tasks for end-users and coordinate projects with the Senior Technology Officer and team members.
